[book]
authors = ["funkill2"]
language = "ru"
multilingual = false
src = "src"
title = "Язык программирования Rust"

[output.html]
google-analytics="UA-142155799-10"
additional-css = ["theme/first-edition.css"]

[output.html.playpen]
editable = true
editor = "ace"
